language: node_js
node_js:
  - "0.8"
  - "0.10"
before_install:
  - npm install phantom-jasmine -g
script: phantomjs --web-security=false www/spec/lib/jasmine-1.2.0/run_jasmine_test.coffee www/spec_console.html